runtime: python39  # Use the appropriate Python version
entrypoint: streamlit run apk.py --server.port=8080 --server.address=0.0.0.0

instance_class: F2  # Choose an instance class (F2 is a good starting point)

handlers:
  - url: /.*
    script: auto
    secure: always  # Enforce HTTPS
