[firebase]
credentials_base64 = """ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY3VzdG9tZXJjaHVybnByZWRpY3Rpb24tZjdhNGMiLAogICJwcml2YXRlX2tleV9pZCI6ICI3NjAyYjEyMjZhN2ZlODkzYjUwMTQxYmI0OWE2NDAwNTYxYmU4NDBjIiwKICAicHJ..."""
