
[firebase]
credentials_base64 = """ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAiY3VzdG9tZXJj
aHVybnByZWRpY3Rpb24tZjdhNGMiLAogICJwcml2YXRlX2tleV9pZCI6ICIzYjE5MTU4OTIzYzY1
MWE5OGE1YTNiMTBhMzUzY2E3YmU1MGU1YmZhIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJ
TiBQUklWQVRFIEtFWS0tLS0tXG5NSUlFdlFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLY3dn
Z1NqQWdFQUFvSUJBUUNNMjNUOFJMTnNQajUxXG4rUnV2aFdqb0lNZndpSGdENkxWKzBic2pYeXpE
YWwrMWVKak9WVjhoYndyOUJJZkZmRExzUTIyWFhRdkd0ZlJnXG5PNFpyZ21SU1JFVWtoVFE4eG5k
aVpEd1RFNzBGZnZ3TlFYSkVmbC9WNmg4eWxRa2s2WXk5Z3E5UFRtTVRBbUxKXG5BOENRNEdjWnds
UzFZUlBwSnk1aU1VdlIxaUtsY01jQnBOSTMzRzVHckxRUWFDMUFGdkRuVFgvNllmUFVCRVAzXG5x
dkxoaVVxckYyeU9BV0dYanRPYWFkWlhqa2lrcTg1Wlk2SkNpUGE1T2Y4WGxWL253RlJSSlI2Z2RB
aDg1SnpoXG5SN2Q4UXFYaEpsSGdCVnlxT2pNaEl5K2lkSTBvTi94bkZTL2FtN09hK2lhWERQRlBn
eVJaUVlrcEF3dDlpTms5XG5wRHR1VE9wbEFnTUJBQUVDZ2dFQUEwYXFaS0NqYktuUThaVDY0aHp2
K1BBa1BsR3FPdXNMWjVqd3FZeXg0WlNrXG5oN2UzbEJyenRMY2NzaEJNS1JsdnBNT1h0YXpHRkpm
UVNIbXg4V2V0dGlVYzE1SGFpbXhTUkFGUlRWOUk1dXNTXG5hU3VEd1JpUVdZMFJyeTg4c0hWWEh1
UStlQkY2Wit1SENTWlRjUHNySXJQOG5PQldZbmFWRTFjU3JKMTJubExsXG5rbEY2ajAzb2FRSTcy
cGMxR3l6a29CTHcvdmwxTDRUMk9OMGg2M1ZnY2JIZEdXNkJKczd0cVYwSjRDdFk1eS9hXG40Rzc2
RlBNOFFVNnpOUHhESmhDMUZKNWtURVhhcXBFZmwyL1RDMkJueGx0V2p5UVNwWUx1NDg4OG1xdEFt
em9vXG4rOCtMdFNRTDV2a2l2Wm05UmpLQytMd2llQ3FxWWdaYzVtS1EyU0wyMlFLQmdRREcyV1ox
ODlabXlKWGJPWHRuXG5kWmhEaDFxNmdUdHpQTm1VM0FrUTZGTFVZTXdhVE1rdncxZ3FueHpzM2p0
SjIrKzgyMmppQmZqNURWZEd3N3dHXG5ITWNhRURFT3hvVVhQQjc3VHBEOHhDSUNlaEhHQ1dsSHJU
THhQakl2UTZudC9GYXV2dTZOcTJJUkZTTWxUN1h4XG5oTEpBVEs3S1JIQk80aUJ5aG1pRU9wMlBI
UUtCZ1FDMVZ6ZzFhK0FleEpBTURWOXpUZlYra0ZsZ3dpelF5b2o5XG5mSkNUL0pzZmtzRnMvbEMr
V2c2eFZJaHozM3czRllkeVpNVDJQc2JLNXFKWnA5ODAzMXloWFBiRFhSNnhYRm55XG5tWHpxVExz
ZzBZQWlIY3lIbWVHeDNvMnNNMUR2eXFJcEFaOUM5M2J1RGtDR3pXa1RNNGNXK3lGaTJNcytmRXVt
XG45U0VPWUc3OTZRS0JnRm1SYzJXTi8vVXNSTlFLZ0Z1SnpKd2VTKy9XWmtEeUY4L0ZqUS9nbGU2
ejZ6dXRlckhZXG4rODIyL2dCejJhRGJRSkdCQXkxTUkybUxhTlNuTmZwSzNDUVJSd2V3eENKRElu
RndZajU0Mmhqamd6NEEzenM1XG4rTWhSaTZsZWdSeUJuVW41RnRzWlo0THFVbnByL1RoYzNTMjVY
TUlmTWJkV2crY1NRK0hMeFV6QkFvR0FQb2x5XG5wL0dvMjlON3ZieEs0NC9LRHJpbktoZ3NybUI2
ZDdpaWYzYUk1STJPeVJDM05iNEcvUjZpNUJyNVVtSEpVU2p4XG5SOTZFWGVyRnFGZWRRVFdhVTBl
bERlQ3FPZzRZTXZLOXdtdHR5VGFXa3ExbUlJbHY3UkJNR1V1bEtOemZxWGFXXG52dGhxbWxRdDZv
OGlJbTROczE0dHVGSDlYWEl1QU1qZWVuL0ZKeWtDZ1lFQXhJRTF2UDFHY05nSnhPZStseU9kXG5K
dHp1b3h0YWVvK0U4SXNocStHbCtvZnpzdEdYSVdsMmdhc1dDUEtUQ0xRbzdYdUI3L2hwV0llTEVw
RFFqTk51XG4wT3JsOThaRU9tNjdmeHBTVDhSTlY3clVvSVZKM2NxWHlaUy95WHlGNkNlOWVaNEdB
bCt0bEg2TVp0YTlVSGhPXG5PMzYwRUtPZm1Uemphb2JxaCtDL3h2TT1cbi0tLS0tRU5EIFBSSVZB
VEUgS0VZLS0tLS1cbiIsCiAgImNsaWVudF9lbWFpbCI6ICJmaXJlYmFzZS1hZG1pbnNkay1mYnN2
Y0BjdXN0b21lcmNodXJucHJlZGljdGlvbi1mN2E0Yy5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIs
CiAgImNsaWVudF9pZCI6ICIxMDc4ODAxNzI4ODg4NDcyOTkzNTAiLAogICJhdXRoX3VyaSI6ICJo
dHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvYXV0aCIsCiAgInRva2VuX3VyaSI6
ICJodHRwczovL29hdXRoMi5nb29nbGVhcGlzLmNvbS90b2tlbiIsCiAgImF1dGhfcHJvdmlkZXJf
eDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9vYXV0aDIvdjEvY2Vy
dHMiLAogICJjbGllbnRfeDUwOV9jZXJ0X3VybCI6ICJodHRwczovL3d3dy5nb29nbGVhcGlzLmNv
bS9yb2JvdC92MS9tZXRhZGF0YS94NTA5L2ZpcmViYXNlLWFkbWluc2RrLWZic3ZjJTQwY3VzdG9t
ZXJjaHVybnByZWRpY3Rpb24tZjdhNGMuaWFtLmdzZXJ2aWNlYWNjb3VudC5jb20iLAogICJ1bml2
ZXJzZV9kb21haW4iOiAiZ29vZ2xlYXBpcy5jb20iCn0K"""
